# Generated by Django 5.0.2 on 2024-02-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merk',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
