# Generated by Django 5.0.2 on 2024-02-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silci', '0002_alter_merk_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='merk',
        ),
        migrations.AddField(
            model_name='barang',
            name='merk',
            field=models.ManyToManyField(blank=True, null=True, to='silci.merk'),
        ),
    ]
