# Generated by Django 5.0.2 on 2024-02-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silci', '0003_remove_barang_merk_barang_merk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='merk',
            field=models.ManyToManyField(blank=True, null=True, related_name='barang', to='silci.merk'),
        ),
    ]
