# Generated by Django 4.2.10 on 2024-02-29 17:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pabrik',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BarangPabrik',
            fields=[
                ('id_barang', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stok', models.IntegerField()),
                ('id_pabrik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barang', to='pabrik.pabrik')),
            ],
        ),
    ]
