# Generated by Django 4.2.10 on 2024-02-29 19:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pabrik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangpabrik',
            name='id_pabrik',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='barangpabrik', to='pabrik.pabrik'),
        ),
        migrations.AlterUniqueTogether(
            name='barangpabrik',
            unique_together={('id_barang', 'id_pabrik')},
        ),
    ]
