# Generated by Django 4.2.10 on 2024-02-29 19:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0006_alter_perusahaanimpor_logo'),
        ('pabrik', '0002_alter_barangpabrik_id_pabrik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangpabrik',
            name='id_barang',
            field=models.ForeignKey(default=uuid.uuid4, editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='barang', serialize=False, to='barang.barang'),
        ),
        migrations.AlterField(
            model_name='barangpabrik',
            name='id_pabrik',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='pabrik', to='pabrik.pabrik'),
        ),
    ]
