# Generated by Django 4.2.10 on 2024-02-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabrik', '0003_alter_barangpabrik_id_barang_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barangpabrik',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='barangpabrik',
            constraint=models.UniqueConstraint(fields=('id_barang', 'id_pabrik'), name='unique_barang_pabrik'),
        ),
    ]
