# Generated by Django 5.0.2 on 2024-03-01 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0006_alter_perusahaanimpor_logo'),
        ('pabrik', '0005_alter_barangpabrik_stok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangpabrik',
            name='id_barang',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='barang.barang'),
        ),
    ]
