# Generated by Django 5.0.2 on 2024-03-01 05:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0006_alter_perusahaanimpor_logo'),
        ('pabrik', '0007_alter_barangpabrik_id_barang'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='barangpabrik',
            name='unique_barang_pabrik',
        ),
        migrations.RenameField(
            model_name='barangpabrik',
            old_name='id_pabrik',
            new_name='pabrik',
        ),
        migrations.RemoveField(
            model_name='barangpabrik',
            name='id_barang',
        ),
        migrations.AddField(
            model_name='barangpabrik',
            name='barang',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='barang_pabrik', serialize=False, to='barang.barang'),
        ),
        migrations.AddConstraint(
            model_name='barangpabrik',
            constraint=models.UniqueConstraint(fields=('barang', 'pabrik'), name='unique_barang_pabrik'),
        ),
    ]
