# Generated by Django 5.0.2 on 2024-03-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabrik', '0008_remove_barangpabrik_unique_barang_pabrik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pabrik',
            name='nama',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
