# Generated by Django 5.0.3 on 2024-04-02 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0007_alter_barang_nama_alter_merk_nama'),
        ('gudang', '0004_alter_baranggudang_gudang'),
        ('pabrik', '0009_alter_pabrik_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermintaanPengiriman',
            fields=[
                ('kode_permintaan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('jumlah', models.IntegerField()),
                ('status', models.IntegerField()),
                ('waktu_permintaan', models.DateTimeField(auto_now_add=True)),
                ('tanggal_pengiriman', models.DateField(blank=True, null=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.barang')),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gudang.gudang')),
                ('pabrik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pabrik.pabrik')),
            ],
        ),
    ]
