# Generated by Django 5.0.4 on 2024-04-03 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barang", "0019_alter_pengadaanbarangimpor_status"),
        ("pabrik", "0010_permintaanpengiriman"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchProduksi",
            fields=[
                (
                    "kode_produksi",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("jumlah", models.IntegerField(default=0)),
                ("tanggal_produksi", models.DateField()),
                ("status", models.IntegerField(default=1)),
                (
                    "barang",
                    models.ForeignKey(
                        default=uuid.uuid4,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barang_batch",
                        to="barang.barang",
                    ),
                ),
                (
                    "pabrik",
                    models.ForeignKey(
                        default=uuid.uuid4,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pabrik_batch",
                        to="pabrik.pabrik",
                    ),
                ),
            ],
        ),
    ]
