# Generated by Django 5.0.3 on 2024-03-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0007_alter_barang_nama_alter_merk_nama'),
        ('gudang', '0004_alter_baranggudang_gudang'),
        ('pabrik', '0010_permintaanpengiriman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permintaanpengiriman',
            old_name='pabrik',
            new_name='id_pabrik',
        ),
        migrations.RemoveField(
            model_name='permintaanpengiriman',
            name='barang',
        ),
        migrations.RemoveField(
            model_name='permintaanpengiriman',
            name='gudang',
        ),
        migrations.AlterField(
            model_name='permintaanpengiriman',
            name='id_barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.barang'),
        ),
        migrations.AlterField(
            model_name='permintaanpengiriman',
            name='id_gudang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gudang.gudang'),
        ),
        migrations.AlterField(
            model_name='permintaanpengiriman',
            name='jumlah',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='permintaanpengiriman',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permintaanpengiriman',
            name='waktu_permintaan',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterModelTable(
            name='permintaanpengiriman',
            table='permintaan_pengiriman',
        ),
    ]
