# Generated by Django 5.0.4 on 2024-04-04 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pabrik", "0011_batchproduksi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchproduksi",
            name="tanggal_produksi",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
