# Generated by Django 5.0.4 on 2024-04-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pabrik", "0012_alter_batchproduksi_tanggal_produksi"),
    ]

    operations = [
        migrations.AddField(
            model_name="barangpabrik",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
