# Generated by Django 5.0.2 on 2024-02-28 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('deskripsi', models.TextField()),
                ('harga', models.BigIntegerField()),
                ('merk', models.ManyToManyField(blank=True, null=True, related_name='barang', to='barang.merk')),
            ],
        ),
    ]
