# Generated by Django 5.0.2 on 2024-02-28 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='merk',
        ),
        migrations.AddField(
            model_name='barang',
            name='merk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barang.merk'),
        ),
    ]
