# Generated by Django 5.0.2 on 2024-02-28 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0002_remove_barang_merk_barang_merk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='merk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barang', to='barang.merk'),
        ),
    ]
