# Generated by Django 5.0.2 on 2024-02-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0005_perusahaanimpor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perusahaanimpor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo perusahaan/'),
        ),
    ]
