# Generated by Django 5.0.2 on 2024-03-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0006_alter_perusahaanimpor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='nama',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='merk',
            name='nama',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
