# Generated by Django 5.0.2 on 2024-03-25 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0007_alter_barang_nama_alter_merk_nama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perusahaanimpor',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perusahaan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perusahaanimpor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logoperusahaan/'),
        ),
    ]
