# Generated by Django 5.0.2 on 2024-03-28 04:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0008_perusahaanimpor_admin_alter_perusahaanimpor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perusahaanimpor',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
