# Generated by Django 5.0.2 on 2024-03-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0010_alter_perusahaanimpor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perusahaanimpor',
            name='logo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
