# Generated by Django 5.0.2 on 2024-03-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0011_alter_perusahaanimpor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perusahaanimpor',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
