# Generated by Django 5.0.2 on 2024-04-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0012_alter_perusahaanimpor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perusahaanimpor',
            name='nama',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
