# Generated by Django 5.0.2 on 2024-04-01 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0013_alter_perusahaanimpor_nama'),
        ('pabrik', '0009_alter_pabrik_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengadaanBarangImpor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jumlahBarang', models.IntegerField()),
                ('totalHarga', models.BigIntegerField()),
                ('tanggalPermintaaan', models.DateTimeField(auto_now_add=True)),
                ('tanggalUpdate', models.DateTimeField(auto_now=True)),
                ('fileInvoice', models.TextField()),
                ('filePayment', models.TextField()),
                ('barang', models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='barang.barang')),
                ('pabrikTujuan', models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='pabrik.pabrik')),
                ('perusahaan', models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='barang.perusahaanimpor')),
            ],
        ),
    ]
