# Generated by Django 5.0.2 on 2024-04-01 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0014_pengadaanbarangimpor'),
        ('gudang', '0004_alter_baranggudang_gudang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengadaanbarangimpor',
            name='pabrikTujuan',
        ),
        migrations.AddField(
            model_name='pengadaanbarangimpor',
            name='gudangTujuan',
            field=models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='gudang.gudang'),
        ),
    ]
