# Generated by Django 5.0.2 on 2024-04-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0015_remove_pengadaanbarangimpor_pabriktujuan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengadaanbarangimpor',
            name='fileInvoice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pengadaanbarangimpor',
            name='filePayment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
