# Generated by Django 5.0.2 on 2024-04-01 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0016_alter_pengadaanbarangimpor_fileinvoice_and_more'),
        ('gudang', '0004_alter_baranggudang_gudang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengadaanbarangimpor',
            name='barang',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='barang.barang'),
        ),
        migrations.AlterField(
            model_name='pengadaanbarangimpor',
            name='gudangTujuan',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='gudang.gudang'),
        ),
        migrations.AlterField(
            model_name='pengadaanbarangimpor',
            name='perusahaan',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='barang.perusahaanimpor'),
        ),
    ]
