# Generated by Django 5.0.2 on 2024-04-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0017_alter_pengadaanbarangimpor_barang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengadaanbarangimpor',
            name='status',
            field=models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], default=1),
        ),
    ]
