# Generated by Django 5.0.2 on 2024-04-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0018_pengadaanbarangimpor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengadaanbarangimpor',
            name='status',
            field=models.IntegerField(choices=[(0, 'Permintaan Ditolak'), (1, 'Penawaran Dikirim'), (2, 'Menunggu Pembayaran'), (3, 'Pembayaran Dikirim'), (4, 'Pembayaran Diverifikasi'), (5, 'Barang Dalam Perjalanan'), (6, 'Barang Diterima')], default=1),
        ),
    ]
