# Generated by Django 5.0.2 on 2024-03-01 05:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0006_alter_perusahaanimpor_logo'),
        ('gudang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangGudang',
            fields=[
                ('barang', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='barang_gudang', serialize=False, to='barang.barang')),
                ('stok', models.IntegerField(default=0)),
                ('gudang', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='gudang', to='gudang.gudang')),
            ],
        ),
        migrations.DeleteModel(
            name='JenisMerk',
        ),
        migrations.AddConstraint(
            model_name='baranggudang',
            constraint=models.UniqueConstraint(fields=('barang', 'gudang'), name='unique_barang_gudang'),
        ),
    ]
