# Generated by Django 5.0.2 on 2024-03-01 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0003_alter_baranggudang_gudang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baranggudang',
            name='gudang',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='gudang', to='gudang.gudang'),
        ),
    ]
